---
files:
  include: src/themes/**/*.s+(a|c)ss
options:
  formatter: html
  max-warnings: 50
  merge-default-rules: true
  output-file: linters/sass-lint.html
rules:
  e-attribute-nesting:
    - 0
  empty-line-between-blocks:
    - 0
    -
      ignore-single-line-rulesets: true
  extends-before-declarations: 2
  extends-before-mixins: 2
  final-newline:
    - 0
    -
      include: false
  force-attribute-nesting: 0
  force-element-nesting: 0
  force-pseudo-nesting: 0
  hex-notation:
    - 2
    -
      style: uppercase
  indentation:
    - 2
    -
      size: 4
  mixins-before-declarations:
    - 2
    -
      exclude:
        - breakpoint
        - mq
  no-debug: 1
  no-ids: 2
  no-important: 0
  no-vendor-prefixes:
    - 2
    -
      excluded-identifiers:
        - webkit
      ignore-non-standard: true
  no-warn: 1
  placeholder-in-extend: 2
  property-sort-order:
    - 1
    -
      ignore-custom-properties: true
      order:
        - display
        - margin
  single-line-per-selector:
    - 0
  space-between-parens:
    - 1
    -
      include: false
  variable-for-property:
    - 2
    -
      properties:
        - margin
        - padding
        - color
        - background-color
        - font-size
        - line-height
        - font-weight
