# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - env:
        NODE_OPTIONS: --max_old_space_size=4096
    - run: npm ci
    - run: npm run lint:lib
    - run: npm run build:lib
    - run: npm run test:lib:perf
    - run: npm run test:lib:others
    - run: npm run test:lib:grid
    - run: npm run test:lib:tgrid
    - run: npm run test:lib:hgrid
    - run: npm run test:schematics
