# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master, '[0-9]+.[0-9]+.x' ]
  pull_request:
    branches: [ master, '[0-9]+.[0-9]+.x' ]

jobs:
  run-tests:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run lint:lib
    - run: npm run build:lib
    - run: npm run test:lib:others
      env:
        NODE_OPTIONS: --max_old_space_size=4096
    # - run: npm run test:lib:grid
    #   env:
    #     NODE_OPTIONS: --max_old_space_size=4096
    # - run: npm run test:lib:tgrid
    #   env:
    #     NODE_OPTIONS: --max_old_space_size=4096
    # - run: npm run test:lib:hgrid
    #   env:
    #     NODE_OPTIONS: --max_old_space_size=4096
    - run: npm run test:schematics

  coverage:
    needs: run-tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [14]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install coverage combiner, combine scripts and deploy results to coveralls.io
      if: github.repository == 'IgniteUI/igniteui-angular'
      run: |
        npm i istanbul-combine
        istanbul-combine -d coverage -p none -r lcov -r cobertura coverage/hierarchical-grid/coverage-final.json coverage/tree-grid/coverage-final.json coverage/non-grid/coverage-final.json coverage/grid/coverage-final.json
        cat ./coverage/lcov.info | coveralls

